language: cpp
sudo: false
dist: trusty
addons:
  apt:
    packages: qtbase5-dev qttools5-dev-tools
before_install:
  - QT_SELECT=qt5 qmake
# FIXME: disable `make test` for now, because Travis-CI's Qt installation is
# broken (lacks fonts(?)).  This doesn't happen on Ubuntu 16.04 or 18.04, so
# for now I'll run tests manually and hope that Travis-CI updates their Ubuntu
# image soon.
script:
  - make
